### ISSUE TITLE
It should be easier to "chain" children

### ISSUE THREAD

**Issue by asthasr** [psFried/roperator#12]
*Motivated by [this comment](https://github.com/psFried/roperator/issues/8#issuecomment-569126012) and moved from that issue.*

> One thought did cross my mind about this. When you want the operator to create a namespace and then resources within that namespace, you need to of course create the namespace before the resources within it. Your handler would have to first return a syncResponse with only then namespace resource, and then create the rest of the child resources later, after the namespace shows up in the syncRequest children. This type of thing would probably make an excellent example. I'll try to create a basic example that shows how to do that, since it's likely that others would benefit from it as well.

So, that explains why it was failing on the first request and then succeeding on the second. It makes sense, but I had been thinking of it as equivalent to applying a YAML manifest, which obviously is higher level than this.

I have implemented the logic you suggest, and it seems to work pretty well:

```rust
/// Encapsulates the creation of the child objects (e.g., `Namespace` and `Rolebinding`) and
/// returns a list of opaque JSON objects for syncing. Note that it returns only the namespace if a
/// namespace is not included in the `SyncRequest`, and then creates a `RoleBinding` in a
/// subsequent request.
pub fn create_child_objects(request: &SyncRequest) -> anyhow::Result<Vec<Value>> {
    let parent: DevSandbox = request.deserialize_parent()?;
    let mut children: Vec<Value> = Vec::new();
    let names = Names::new(&parent)?;
    let ns = create_namespace(&names).map(serde_json::to_value)??;
    children.push(ns);
    if request.has_child("v1", "Namespace", "", &names.namespace) {
        info!("Namespace exists; creating rolebinding");
        let rb = create_rolebinding(&names).map(serde_json::to_value)??;
        children.push(rb);
    } else {
        info!("Namespace does not exist; creating it");
    }
    Ok(children)
}
```

It strikes me as a little odd that there's no way to check whether something exists using one of the JSON objects. What if you could use a method like `request.has_child_value(ns)` to check for a child with a given serializable JSON object?

**Comment by asthasr** [comment]
Another thought: what if the children could be constructed once in a tree-like structure?

```rust
let mut children = ChildTree::new();
children.add(ns).and_then(rb);
```

**Comment by psFried** [comment]
Yeah, I think that the API for accessing children on the `SyncRequest` could be a lot easier to use. There's issue #2 to track some of the breaking changes that I was thinking about. But I think it's also a good idea to have accessor functions that accept a json `&Value`, since it can be simpler to just create the json and then check if you want to add it to the response. Perhaps we can keep this issue to track adding those functions specifically, and keep #2 just for the other (breaking) changes.

> Another thought: what if the children could be constructed once in a tree-like structure?

I agree that it would also be nice to improve the API for adding children to the response. I don't know if I'm really sold on it being a tree structure thought, since the only hierarchy I can think of would always just have a namespace as the parent, and it's unclear how it should affect how the response is handled by the framework. Do you have any ideas for how we should handle a tree-like response? 

There is also an  [existing function](https://docs.rs/roperator/0.1.2/roperator/handler/struct.SyncResponse.html#method.add_child) for adding children more easily, but if there's others that would be convenient, then I'd be all for adding them.

**Comment by asthasr** [comment]
I could see a need for namespace-like behavior in creating and instantiating CRDs, or waiting for a child CRD to achieve some status before syncing another object...

**Comment by psFried** [comment]
Circling back on this, now that I've gotten into some of the breaking changes for 0.2.x. While this seemed at first like it would be really straight forward, and still seems like it would be useful, I've realized that the semantics are a little more tricky than I expected. The issue is that a resource can _exist_ in the `SyncRequest`, but that doesn't necessarily mean that it's in a good state. For example, a Namespace resource could be _present_, but what if it's in the process of being deleted. Or a Pod could be present, but the status could indicate that it's no longer actually running.

Rather than try to come up with defined semantics for each of those cases separately, I think the way to go is to have a "query-by-example" function that will look up a child resource from the `RequestChildren` and just return it. That way, developers can look at whatever fields they want to determine how to proceed. This will still save you from having to manually get the id and type information in order to pass to the `RequestChildren` functions. But it also won't hide any of the essential complexity of Kubernetes. This is in PR #19
