### ISSUE TITLE
CronJob in k8s_types is defined under the wrong version number.

### ISSUE THREAD

**Issue by edwardgeorge** [psFried/roperator#32]
CronJob in `k8s_types.rs` is defined as under the `v1` batch api, but it does not exist in this version. It exists under `v1beta1` and is not in `v1`.

This has the effect that if you specify `.with_child(k8s_types::batch::v1::CronJob, ...)` on your operator config then you get no events at all being processed, the operator appears to hang and do nothing. (which may perhaps be a separate bug?)

**Comment by psFried** [comment]
> the operator appears to hang and do nothing. (which may perhaps be a separate bug?)

You should see the errors in both the logs and the Prometheus metrics. Additionally, the health check endpoint should report an unhealthy status since the initial state could never be determined. If any of those things aren't working, then I'd definitely appreciate a bug report.

The expected behavior is for the operator to just keep retrying, though. The idea being that it'll eventually get restarted due to the failing health check. The reason we retry even when the resource type doesn't exist is that it's common to deploy both the crd and the operator at the same time, so it's expected for resource endpoints to potentially appear after the operator is already started.

**Comment by psFried** [comment]
I closed this when merging the PR since that addresses the immediate problem, but feel free to open a new issue if there's anything more on the error handling topic.
