### ISSUE TITLE
Comparison to operator based on kube-rs

### ISSUE THREAD

**Issue by xavier83** [psFried/roperator#41]
I recently came across an rust operator example at https://github.com/Pscheidl/rust-kubernetes-operator-example which uses [kube-rs](https://github.com/kube-rs/kube-rs) 

Does roperator implement similar approach. Can it make use of kube-rs?

**Comment by psFried** [comment]
In terms of the difference I see between the two projects, kube-rs is mostly concerned with being a compatible and complete API client. Roperator is more of an opinionated framework for the very specific task of building operators. Roperator could use kube-rs in order to make api requests, and I even started off using it initially. But I really wanted to treat API resources very generically, and it ended up feeling simpler to use an http library directly.

In terms of the approach, I'd say that the example in the link seems rather different from that of roperator, but it's also not really a fair comparison. There's lots of cases that roperator handles that aren't covered in that example. For instance, roperator handles updates to the CRD which then affect the desired state of "child" resources, and cleaning up those that are no longer needed. If you want an easy way to get an operator going that handles all the usual operator things correctly, then roperator was made for you. But if you need lower-level control over exactly how your reconciliation API calls will be made, then kube-rs would be an excellent choice.
